profiles/urls.py
from django.conf.urls import url

from . import views





app_name = 'profiles'

urlpatterns = [
    url(r'^$',views.BaseView.as_view(),name='base'),
    url(r'^register/$',views.RegisterView.as_view(),name='register'),
    url(r'^login/$',views.SignInView.as_view(),name='login'),
    url(r'^logout/$',views.SignOutView.as_view(),name='logout'),
    
]

src/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^',include('profiles.urls')),
]

profiles/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager as Manager
from django.db import models
from PIL import Image


class UserManager(Manager):
    use_in_migrations =True

    def _create_user(self,email,password,**kwargs):

        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        username = email.split('@',1)[0]
        user = self.model(username=username,email=email,**kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self,email=None,password=None,**kwargs):
        kwargs.setdefault('is_staff',False)
        kwargs.setdefault('is_superuser',False)

        return self._create_user(email,password,**kwargs)

    def create_superuser(self,email,password,**kwargs):
        kwargs.setdefault('is_staff',True)
        kwargs.setdefault('is_superuser',True)

        if kwargs.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if kwargs.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email,password,**kwargs)




class User(AbstractUser):

    username = models.CharField(max_length=30,unique=True)
    email = models.EmailField('Email Address',unique=True,blank=False,null=False)

    USERNAME_FIELD  = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()



class Profile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE,editable=False)
    screen_name = models.CharField(max_length=30,blank=True,null=True)
    location = models.CharField(max_length=30,blank=True,null=True)
    adds_added = models.IntegerField(default=0)
    profile_pic = models.ImageField(upload_to=settings.MEDIA_URL)


    def __str__(self):
        return self.user.username

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import get_user_model
from .models import Profile
User = get_user_model()

class RegisterForm(UserCreationForm):

    email = forms.EmailField(widget=forms.EmailInput, required=True)


    class Meta(UserCreationForm.Meta):

        model = User
        fields = ('email','password1','password2',)


    def save(self, commit=False):
        user = User.objects.create_user(
                                        self.cleaned_data.get('email'),
                                        self.cleaned_data.get('password1')
                                        )
        if commit:
            user.save()
        return user


class LoginForm(AuthenticationForm):

    def clean(self):
        return super(LoginForm,self).clean()

class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = '__all__'
        

profiles/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView,LoginView
from django.contrib.auth import login,authenticate
from django.conf import settings
from django.http import Http404
from django.shortcuts import render,HttpResponseRedirect,reverse,get_object_or_404
from django.views.generic import TemplateView,FormView,DetailView,UpdateView,ListView
from .forms import RegisterForm,AuthenticationForm,ProfileForm
from .models import Profile

User = get_user_model()

class BaseView(TemplateView):
    template_name = 'profiles/base.html'

    def get(self,request,*args,**kwargs):
        template_name = 'profiles/base.html'
        qs = User.objects.all().order_by('-date_joined')[:5]
        return render(request,template_name,{'users':qs})


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'profiles/register.html'
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        login(self.request,user)
        return HttpResponseRedirect(reverse('profiles:base'))

class SignOutView(LogoutView):
    next_page = settings.LOGOUT_REDIRECT_URL
    template_name = 'profiles/base.html'


class SignInView(LoginView):
    template_name = 'profiles/login.html'
    redirect_field_name = settings.LOGIN_REDIRECT_URL

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        user = form.get_user()
        login(self.request, user)
        return HttpResponseRedirect(reverse(settings.LOGIN_REDIRECT_URL),{'user':user})

profiles/templates/profiles/base.html
{% extends 'base.html' %}
{% block title %}{{block.super}}{% endblock %}
{% block profiles %}
{% if user.is_authenticated %}
  <li role="presentation" class="dropdown">{% block register %}
    <a href='{% url 'profiles:base'  %}' class="dropdown-toggle" id='ProfileDD' data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
             <i class="fa fa-user-circle-o" style='font-size:130%;'aria-hidden="true"></i>
             {{request.user.username}}  <span class="caret"></span></a>
             <ul class="dropdown-menu" aria-labelledby="ProfileDD">
                  <li><a href="{% url 'profiles:base'  %}">Profile</a></li>
                  <li><a href="{% url 'profiles:base'  %}">Edit Profile</a></li>
                  <li><a href="{% url 'profiles:base' %}">All Profiles</a></li>
                  {% if user.is_authenticated and user.is_superuser %}
                  <li><a href="admin/">Admin</a></li>
                {% endif %}
                  <li role="separator" class="divider"></li>
                  <li><a href={% url 'profiles:logout' %}>Logout</a></li>
             </ul>
      {% endblock %}</li>
  <li>{% block login %}<a href={% url 'profiles:logout' %}>Logout</a>{% endblock %}</li>
{% else %}
  <li {% block regis %}{% endblock %}><a href={% url 'profiles:register' %}>Register</a></li>
  <li {% block logi %}{% endblock %}><a href={% url 'profiles:login' %}>Sign In</a></li>
{% endif %}
{% endblock %}
{% block main %}
<h1>Profiles Base Template</h1>
{% endblock %}

profiles/templates/profiles/login.html
{% extends 'profiles/base.html' %}
{% block title %}Login | {{block.super}}{% endblock %}
{% block logi %}class='active'{% endblock %}

{% block main %}

<div class="row">
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-login">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-6">
        <h3 id="register-form-link">Sign In:</h3>
      </div>
    </div>
    <hr>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-12">
        <form id="register-form" action={% url 'profiles:login' %} method="post" role="form" style="display: block;">
          {% csrf_token %}
          {% if form.non_field_errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{form.non_field_errors}}</strong>
          </div>
          {% endif %}
          {% for field in form %}
          {% if field.errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{field.label}}: </strong>{% for error in field.errors %}{{error}}{% endfor %}
          </div>
          {% endif %}
          {% endfor %}
          <div class="form-group">
            <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="your-email@example.com" value="">
          </div>
          <div class="form-group">
            <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Choose a password">
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-6 col-sm-offset-3">
                <input type="submit" name="submit" id="register-submit" tabindex="4" class="form-control btn btn-primary" value="Sign In">
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-lg-12">
                <div class="text-center">
                  <a href="#" tabindex="5" class="forgot-password">Forgot Password?</a>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<!--
<form method="post">
{% csrf_token %}
{{form.as_table}}
<button class='btn btn-info' type='submit' value='Sign Up'>Sign Up</button>
</form>
-->

{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'profiles/base.html' %}
{% block title %}{{profile.username}} | {{block.super}}{% endblock %}
{% block main %}
<h1>User Profile Template</h1>
{{profile.username}}
{% endblock %}

profiles/templates/profiles/profile_edit.html
{% extends 'profiles/base.html' %}
{% block title %}{{user.username}} - Edit Profile{% endblock %}
{% block main %}


<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-login">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-8">
        <h5>Edit Profile:</h5>
        <h3 id="register-form-link">{{user.username}}</h3>
      </div>
    </div>
    <hr>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-lg-12">
        <form id="profile-form" action={% url 'profiles:edit' %} method="post" role="form" style="display: block;">
          {% csrf_token %}
          {% if form.non_field_errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{form.non_field_errors}}</strong>
          </div>
          {% endif %}
          {% for field in form %}
          {% if field.errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{field.label}}: </strong>{% for error in field.errors %}{{error}}{% endfor %}
          </div>
          {% endif %}
          {% endfor %}
          <div class="form-group">
            <input type="text" name="screen_name" id="id_screen_name" tabindex="1" class="form-control" placeholder="Name you want appear on our website" value="">
          </div>
          <div class="form-group">
            <input type="text" name="location" id="id_location" tabindex="2" class="form-control" placeholder="Your location">
          </div>
          <div class="form-group">
            <input type="number" name="adds_added" id="id_adds_added" tabindex="2" class="form-control" placeholder="Your adds count">
          </div>
          <div class="form-group">
            <input type="file" name="profile_pic" id="id_profile_pic" tabindex="2" class="form-control" placeholder='Upload Image'>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-8 col-sm-offset-2">
                <input type="submit" name="submit" id="register-submit" tabindex="4" class="form-control btn btn-primary" value="Save">
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
</div>
{% endblock %}

profiles/templates/profiles/profiles_list.html
{% extends 'profiles/base.html' %}
{% block title %}Profiles | {{block.super}}{% endblock %}
{% block main %}
<h1>User Profiles:</h1>
{% if users %}
{% for user in users %}
<p><a href={% url 'profiles:profile' user.user.username%}>{{user}}</a></p>
<p>{{user.screen_name}}</p>
{% endfor %}
{% endif %}
{% endblock %}

profiles/templates/profiles/register.html
{% extends 'profiles/base.html' %}

{% block reg_active %}class='active'{% endblock %}

{% block main %}
<form method="post">
  {% csrf_token %}
  {{form.as_td}}
  <button type="submit">Sign Up</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Oglasnik.mk{% endblock %}</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
  <style>
        @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700,300);
        footer { background-color:#0c1a1e; min-height:350px; font-family: 'Open Sans', sans-serif; }
        .footerleft { margin-top:50px; padding:0 36px; }
        .logofooter { margin-bottom:10px; font-size:25px; color:#fff; font-weight:700;}

        .footerleft p { color:#fff; font-size:12px !important; font-family: 'Open Sans', sans-serif; margin-bottom:15px;}
        .footerleft p i { width:20px; color:#999;}

        .paddingtop-bottom {  margin-top:50px;}
        .footer-ul { list-style-type:none;  padding-left:0px; margin-left:2px;}
        .footer-ul li { line-height:29px; font-size:12px;}
        .footer-ul li a { color:#a0a3a4; transition: color 0.2s linear 0s, background 0.2s linear 0s; }
        .footer-ul i { margin-right:10px;}
        .footer-ul li a:hover {transition: color 0.2s linear 0s, background 0.2s linear 0s; color:#ff670f; }

        .social:hover {
             -webkit-transform: scale(1.1);
             -moz-transform: scale(1.1);
             -o-transform: scale(1.1);
         }

         .icon-ul { list-style-type:none !important; margin:0px; padding:0px;}
         .icon-ul li { line-height:75px; width:100%; float:left;}
         .icon { float:left; margin-right:5px;}

         .copyright { min-height:40px; background-color:#000000;}
         .copyright p { text-align:left; color:#FFF; padding:10px 0; margin-bottom:0px;}
         .heading7 { font-size:21px; font-weight:700; color:#d9d6d6; margin-bottom:22px;}
         .post p { font-size:14px; color:#FFF; line-height:20px;}
         .post p span { display:block; color:#8f8f8f;}
         .bottom_ul { list-style-type:none; float:right; margin-bottom:0px;}
         .bottom_ul li { float:left; line-height:40px;}
         .bottom_ul li:after { content:"/"; color:#FFF; margin-right:8px; margin-left:8px;}
         .bottom_ul li a { color:#FFF;  font-size:12px;}
  </style>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
  {% block head %}
  {% endblock %}
</head>
<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
              <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
          			<span class="icon-bar"></span>
        		  </button>
              <a class="navbar-brand" href={% url 'profiles:base' %} id="logo">Oglasnik</a>
        </div>

        <div class="collapse navbar-collapse navHeaderCollapse">
            <ul class="nav navbar-nav navbar-right">
              {% block profiles %}
              {% endblock %}
            </ul>
        </div>
    </div>
</nav>
<main>
  <div class='container'>
    {% block main %}
    {% endblock %}
  </div>
</main>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6 footerleft ">
        <div class="logofooter"> Oglasnik.mk</div>
        <p>Prva oglasuvacka platforma vo makedonija koja mozete da ja modificirate sprema vasite potrebi,ne gubete vreme,prasajte na Oglasnik</p>
        <p><i class="fa fa-map-pin"></i> 210,  Marks Engels 30/1 , Struga - 6330, Makedonija</p>
        <p><i class="fa fa-phone"></i> Phone (India) : +89 70 878 398</p>
        <p><i class="fa fa-envelope"></i> E-mail : info@oglasnik.mk</p>
      </div>
      <div class="col-md-2 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">GENERAL LINKS</h6>
        <ul class="footer-ul">
          <li><a href="#"> Career</a></li>
          <li><a href="#"> Privacy Policy</a></li>
          <li><a href="#"> Terms & Conditions</a></li>
          <li><a href="#"> Client Gateway</a></li>
          <li><a href="#"> Ranking</a></li>
          <li><a href="#"> Case Studies</a></li>
          <li><a href="#"> Frequently Ask Questions</a></li>
        </ul>
      </div>
      <div class="col-md-4 paddingtop-bottom">
        <h6 class="heading7">LATEST POST</h6>
        <div class="post">
          {% if users %}
          {% for user in users %}
          <p>{{user.username}}<span>{{user.date_joined}}</span></p>
          {% endfor %}
          {% endif %}
        </div>
      </div>
      <div class="col-md-2 col-sm-6 paddingtop-bottom">
        <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="timeline" data-height="300" data-small-header="false" style="margin-bottom:15px;" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
          <div class="fb-xfbml-parse-ignore">
            <blockquote cite="https://www.facebook.com/facebook"><a href="https://www.facebook.com/facebook">Facebook</a></blockquote>
            <blockquote cite="https://www.facebook.com/facebook"><a href="https://www.facebook.com/facebook">Twitter</a></blockquote>
            <blockquote cite="https://www.facebook.com/facebook"><a href="https://www.facebook.com/facebook">Google plus</a></blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<!--footer start from here-->
<div class="copyright">
  <div class="container">
    <div class="col-md-6">
      <p>© 2016 - All Rights with Oglasnik.mk</p>
    </div>
    <div class="col-md-6">
      <ul class="bottom_ul">
        <li><a href="#">Oglasnik.mk</a></li>
        <li><a href="#">About us</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Faq's</a></li>
        <li><a href="#">Contact us</a></li>
        <li><a href="#">Site Map</a></li>
      </ul>
    </div>
  </div>
</div>

  <script
          src="https://code.jquery.com/jquery-3.2.1.min.js"
          integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
          integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
          crossorigin="anonymous">
  </script>
  {% block script %}
  {% endblock %}
</body>
</html>